"""
agents_md.py — Framework adapter for the cross-tool ``AGENTS.md`` standard.

Agent files:  .agents/<slug>.md         (plain Markdown, per-specialist detail)
Instructions: AGENTS.md (repo root)      (the canonical single file consumers read)
Format:       Plain Markdown — no YAML front matter
Handoffs:     Inline handoffs removed from the body; routing is preserved in
              references/runtime-handoffs.json (handoff_delivery_mode = "manifest")

Why this target
---------------
``AGENTS.md`` is an emerging cross-tool standard (Agentic AI Foundation / Linux
Foundation, formed Dec 2025): a single repo-root Markdown file read by many AI
coding tools at once — Continue, Cursor, Cline, OpenAI Codex, Zed, Aider, Gemini
CLI, Jules, and more. ``--framework agents-md`` emits one well-formed, *framework-
neutral* ``AGENTS.md`` (the team brief: overview, conventions, the agent roster +
orchestrator routing) as the canonical entry the standard tools consume, plus the
full per-specialist team under ``.agents/`` for humans and agentteams' own tooling.

The standard consumers read ONLY ``AGENTS.md`` — ``.agents/<slug>.md`` are detail
files for humans/version-control, not something those tools parse. ``AGENTS.md`` is
therefore kept self-sufficient (roster + routing inline), not a directory of pointers.

Shared-namespace note: ``--framework goose`` ALSO writes a repo-root ``AGENTS.md``.
The two targets are different invocations, but if a project uses both they share
this path — the emitted file carries a one-line generated notice to that effect, and
``references/bridge-refresh-safety.md`` documents the shared ownership.

This adapter is **generate-only**: it is not a ``--convert-from`` / ``--interop-from``
/ ``--bridge-from`` target (those paths hardcode the instructions filename and would
emit a mislabeled file). The CLI rejects those combinations with a clear error.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .base import FrameworkAdapter
from agentteams.yaml_frontmatter import parse_yaml_front_matter as _parse_yaml_front_matter

# Matches a single-line YAML scalar: key: value (with optional surrounding quotes).
_YAML_SCALAR_RE = re.compile(r'^([a-zA-Z][a-zA-Z0-9_-]*)\s*:\s*"?([^"\n]+)"?\s*$', re.MULTILINE)
# The instructions template opens with a non-YAML "SECTION MANIFEST" HTML comment;
# _strip_yaml_front_matter cannot see it, so it would leak the template filename into
# the published AGENTS.md. Strip exactly that leading comment.
_LEADING_MANIFEST_RE = re.compile(r"\A\s*<!--.*?SECTION MANIFEST.*?-->\s*\n?", re.DOTALL)

# One-line generated notice prepended to AGENTS.md (HTML comment: invisible to the
# tools that consume it, documents the shared-namespace + detail-dir relationship).
_AGENTS_MD_NOTICE = (
    "<!-- AGENTS.md — generated by agentteams. A shared instructions file read by many "
    "AI coding tools (Continue, Cursor, Cline, Codex, Zed, Aider, …). Per-specialist "
    "detail is under .agents/. If this repo also uses `--framework goose`, that target "
    "writes AGENTS.md too — they share this path. -->"
)


def _strip_leading_synthesized_header(body: str, description: str) -> str:
    """Remove a leading ``# Heading`` line, and — if *description* is non-empty
    and immediately follows it — that paragraph too, so re-rendering content
    that already starts with its own heading (either because a prior pass of
    this exact function already ran, or simply because a source agent's own
    body normally opens with ``# {Name}``) doesn't compound into duplicate
    headers on every render (2026-08-11 finding: this was previously
    unconditional, so it duplicated even on a single fresh conversion for the
    normal case, and compounded further on every repeated
    ``--interop-from ... --framework agents-md``/``codex`` re-run).
    """
    lines = body.split("\n")
    if not lines or not lines[0].startswith("# "):
        return body
    idx = 1
    while idx < len(lines) and lines[idx].strip() == "":
        idx += 1
    remainder = "\n".join(lines[idx:])
    if description:
        # Compare the first PARAGRAPH (bounded by the next blank line) to
        # description for equality, not a raw prefix match over the whole
        # remainder (2026-08-11 code-hygiene finding: a prefix match would
        # truncate mid-sentence for a real first paragraph that merely starts
        # with the same text as description but continues, e.g.
        # description="Routes work" against a body paragraph "Routes work to
        # three teams.").
        stripped = remainder.lstrip("\n")
        first_para, _, rest = stripped.partition("\n\n")
        if first_para.strip() == description.strip():
            remainder = rest
    return remainder.strip()


class AgentsMdAdapter(FrameworkAdapter):

    @property
    def framework_id(self) -> str:
        return "agents-md"

    def render_agent_file(self, content: str, agent_slug: str, manifest: dict[str, Any]) -> str:
        """Produce a plain-Markdown per-specialist detail file under ``.agents/``.

        Strips the VS Code YAML front matter and handoff blocks (no consumer of
        these detail files parses them), rewrites ``.github/agents`` path references
        to the ``.agents`` layout, and prepends a ``# {Name}`` heading so each file
        is well-formed standalone Markdown. Idempotent: re-rendering already-
        rendered content (or content that simply already opens with its own
        heading, the normal shape) produces exactly one heading + description,
        not a compounding duplicate — see `_strip_leading_synthesized_header`.
        """
        name, description = _extract_name_description(content, agent_slug, manifest)
        body = self._strip_yaml_front_matter(content)
        body = self._strip_handoffs_section(body)
        body = body.replace(".github/agents", ".agents").strip()
        body = _strip_leading_synthesized_header(body, description)
        header = f"# {name}\n"
        if description:
            header += f"\n{description}\n"
        return f"{header}\n{body}".strip() + "\n"

    def render_instructions_file(self, content: str, manifest: dict[str, Any]) -> str:
        """Render the team brief into a framework-neutral repo-root ``AGENTS.md``.

        Neutralizes the Copilot-authored instructions template (which other
        adapters pass through verbatim): strips the leading SECTION-MANIFEST HTML
        comment, retitles off "Copilot Instructions", rewrites ``.github/agents``
        path references, and rewords Copilot-specific phrasing — so the published
        AGENTS.md carries no tool-specific branding. The AGENTTEAMS fence markers
        are preserved (``--update --merge`` re-renders only the fenced regions).

        A1 (2026-08-15, scoped): appends a ``## Code Style`` section sourced from
        ``manifest["style_rules"]`` when the brief declares any — AGENTS.md's own
        convention (agents.md) is a repo-root file consumers read for exactly this
        kind of project-specific guidance, and ``style_rules`` is a real, populated
        schema field. Cleanly omitted when absent (checks the raw list, not the
        always-non-empty ``style_rules_summary`` placeholder string) rather than
        emitting a hollow "no rules" heading. Scoped to code style only: a
        build/test-commands section was considered and deliberately deferred — no
        schema field exists to source one from (checked directly against
        schemas/project-description.schema.json) — see
        references/agentteams-remediation-log.csv for that follow-up.
        """
        body = self._strip_yaml_front_matter(content)
        body = _neutralize_instructions(body)
        rendered = f"{_AGENTS_MD_NOTICE}\n\n{body}".strip() + "\n"
        style_rules = manifest.get("style_rules")
        if isinstance(style_rules, list) and style_rules:
            lines = "\n".join(f"- {rule}" for rule in style_rules)
            rendered = rendered.rstrip("\n") + f"\n\n## Code Style\n\n{lines}\n"
        return rendered

    def render_builder_file(self, content: str, manifest: dict[str, Any]) -> str:
        """Emit the team-builder meta-agent as a plain-Markdown ``.agents`` detail file."""
        return self.render_agent_file(content, "team-builder", manifest)

    def get_file_extension(self, file_type: str) -> str:
        return ".md"

    def required_front_matter_keys(self) -> tuple[str, ...]:
        """None: these detail files carry no front matter at all.

        `render_agent_file` calls `_strip_yaml_front_matter` and prepends a `# {Name}` heading,
        so an agents_md file is plain Markdown by construction. The empty tuple is the base
        default, but it is stated here so "examined, and the answer is none" is distinguishable
        from "not yet examined" — which is what it was when the audit's per-framework contracts
        were first declared for copilot-vscode and claude only.
        """
        return ()

    def supports_handoffs(self) -> bool:
        return False

    def handoff_delivery_mode(self) -> str:
        # AGENTS.md has no native delegation; preserve routing in the framework-
        # neutral references/runtime-handoffs.json sidecar (machine-recovery only —
        # the standard AGENTS.md consumers do not read it).
        return "manifest"

    def get_agents_dir(self, project_path: Path) -> Path:
        return project_path / ".agents"

    def finalize_output_path(self, rel_path: str, file_type: str) -> str:
        """Map the generic instructions path to repo-root ``AGENTS.md``.

        The planned instructions path is ``../copilot-instructions.md`` relative to
        the agents dir; the agents dir is ``.agents`` (one level under the repo
        root), so the repo root is one level up.
        """
        if file_type == "instructions" and rel_path.endswith("copilot-instructions.md"):
            return "../AGENTS.md"
        return super().finalize_output_path(rel_path, file_type)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _neutralize_instructions(content: str) -> str:
    """Remove Copilot-specific branding/paths from the instructions body so the
    published AGENTS.md is framework-neutral. See render_instructions_file."""
    content = _LEADING_MANIFEST_RE.sub("", content, count=1)
    content = content.replace("— Copilot Instructions", "— Agent Team")
    content = content.replace("all GitHub Copilot agents", "all AI coding agents")
    content = content.replace("GitHub Copilot agents", "AI coding agents")
    content = content.replace(".github/agents", ".agents")
    return content.strip()


def _extract_name_description(
    content: str,
    agent_slug: str,
    manifest: dict[str, Any],
) -> tuple[str, str]:
    """Return (name, description) from the VS Code YAML front matter, with a
    slug-derived fallback when absent."""
    name = ""
    description = ""
    yaml_text, _ = _parse_yaml_front_matter(content)
    if yaml_text is not None:
        for key_match in _YAML_SCALAR_RE.finditer(yaml_text):
            key = key_match.group(1).strip()
            val = key_match.group(2).strip().strip("\"'")
            if key == "name" and not name:
                name = val
            elif key == "description" and not description:
                description = val
    if not name:
        project_name = manifest.get("project_name", "")
        agent_name = FrameworkAdapter._slug_to_name(agent_slug)
        name = f"{agent_name} — {project_name}" if project_name else agent_name
    return name, description
