"""
codex.py — THIN framework adapter for the OpenAI Codex CLI (plan F.4, prep-scoped).

Agent files:  .agents/<slug>.md         (plain Markdown, per-specialist detail —
              Codex has no user-authored persona-file format analogous to
              .claude/agents/*.md or .github/agents/*.agent.md; AGENTS.md content
              is the primary user-facing lever)
Instructions: AGENTS.md (repo root) — Codex loads global instructions from
              ~/.codex/AGENTS.md (or AGENTS.override.md), then walks APPLICABLE
              PROJECT AND NESTED-DIRECTORY AGENTS.md files toward the working
              directory. The team file therefore belongs at the project root;
              nested-directory AGENTS.md files are subdirectory-scoped refinements
              that Codex layers on top when working below the root — operator
              concerns the team pipeline does not emit (documented, not built).
Format:       Plain Markdown — no YAML front matter (delegated to agents_md.py)
Handoffs:     manifest sidecar (references/runtime-handoffs.json), same as agents-md

Research verified via web search 2026-08-10 (plan §6), not assumed from training
knowledge: MCP configuration lives in config.toml, project-scoped via
.codex/config.toml in trusted projects. config.toml MCP emission is implemented —
see agentteams/codex_mcp_emit.py (open-items remediation OPEN-6, 2026-08-10) — opt-in
via the codex:mcp host-feature token. Nested-directory AGENTS.md placement support
remains undone; this adapter's thinness leaves it a registered home.

Delegation: rendering reuses AgentsMdAdapter wholesale (both targets root
AGENTS.md); only the framework id and the generated notice differ. Thin by
design — plan §5.6 / §3 goal 4.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .agents_md import AgentsMdAdapter, _neutralize_instructions

__all__ = ["CodexAdapter"]

# Codex-specific generated notice (HTML comment: invisible to Codex, documents
# the relationship between the root team file and nested-directory walks).
_CODEX_AGENTS_MD_NOTICE = (
    "<!-- AGENTS.md — generated by agentteams for OpenAI Codex. Codex loads "
    "applicable AGENTS.md files as it walks toward the working directory: this "
    "project-root file is the team baseline; nested-directory AGENTS.md files "
    "(if any) layer subdirectory-scoped refinements on top. Per-specialist "
    "detail is under .agents/. MCP servers are configured separately in "
    ".codex/config.toml — emitted by agentteams when the codex:mcp host-feature "
    "token is enabled and the project declares mcp_servers[]; see "
    "agentteams/codex_mcp_emit.py. -->"
)


class CodexAdapter(AgentsMdAdapter):
    """Thin Codex target: agents-md AGENTS.md rendering under a codex identity."""

    @property
    def framework_id(self) -> str:
        return "codex"

    def render_instructions_file(self, content: str, manifest: dict[str, Any]) -> str:
        """Same framework-neutral AGENTS.md as agents-md, Codex-branded notice.

        The neutralization pass is identical (strip Copilot branding/paths,
        keep AGENTTEAMS fence markers); only the generated notice differs so
        the published file documents Codex's nested-directory walk.
        """
        body = self._strip_yaml_front_matter(content)
        body = _neutralize_instructions(body)
        return f"{_CODEX_AGENTS_MD_NOTICE}\n\n{body}".strip() + "\n"

    def get_agents_dir(self, project_path: Path) -> Path:
        # Same detail-file layout as agents-md (Codex has no persona format).
        return project_path / ".agents"
