"""
goose.py — Framework adapter for Block / AAIF "Goose" recipes.

Agent files:  .goose/recipes/<slug>.yaml   (Goose recipe format)
Instructions: AGENTS.md (repo root) + .goosehints (repo root, integrates AGENTS.md)
Format:       Recipe YAML (title, description, instructions, extensions, sub_recipes)
Delegation:   orchestrator handoffs -> sub_recipes  (one delegation layer, native);
              every other agent's handoffs -> `summon` `load(...)` references.

Why this mapping
----------------
agentteams produces an orchestrator that delegates to specialist agents, and
specialists in turn hand off to cross-cutting agents (security, git-operations,
cleanup, ...). Goose caps delegation at ONE layer — a sub-recipe/subagent cannot
spawn another (source: SessionType::SubAgent guard in goose's summon platform
extension). We therefore reinterpret the agentteams handoff DAG faithfully:

  * Depth 0 (orchestrator) -> a recipe declaring `summon` + `sub_recipes` of its
    direct handoff targets. This is TRUE delegation (isolated child sessions).
  * Depth 1+ (every other agent) -> a recipe. Its own handoffs are depth-2 by
    construction, so they are rewritten as `summon` `load("<slug>")` directives
    inside the recipe instructions: the agent loads the referenced recipe's
    content into ITS OWN context instead of spawning a nested delegate. No
    handoff edge is dropped; deeper structure is preserved as references.

See references/plans/goose-integration.plan.md §10 for the full standardized model. The Goose
recipe schema is pinned at version 1.0.0; YAML is emitted by hand (the codebase
intentionally avoids a YAML dependency and parses front matter with regex).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .base import FrameworkAdapter

# ---------------------------------------------------------------------------
# Recipe constants
# ---------------------------------------------------------------------------

_RECIPE_VERSION = "1.0.0"

# Default probe prompt emitted in the orchestrator recipe so `goose run --recipe`
# can be invoked non-interactively in CI without combining with --text (which is
# mutually exclusive with --recipe in Goose CLI).  See W6 in the integration plan.
_ORCHESTRATOR_PROBE_PROMPT = (
    "State your role. For the request 'produce a deliverable for this team', "
    "name the correct workflow and the first agent you would route to."
)

# Regex to locate AGENTTEAMS authority_hierarchy HTML-comment fences in body text.
# These appear in copilot-instructions.md and may appear in orchestrator bodies.
_AUTH_HIER_FENCE_RE = re.compile(
    r"<!--\s*AGENTTEAMS:BEGIN\s+authority_hierarchy\s*-->(.*?)"
    r"<!--\s*AGENTTEAMS:END\s+authority_hierarchy\s*-->",
    re.DOTALL,
)


def _extract_authority_hierarchy(source_instructions: str) -> str:
    """Extract authority_hierarchy fenced block content from copilot-instructions.md."""
    m = _AUTH_HIER_FENCE_RE.search(source_instructions)
    return m.group(1) if m else ""


def _substitute_authority_hierarchy(body: str, hierarchy_content: str) -> str:
    """Replace the authority_hierarchy fenced block in body with project-specific content.

    No-op when hierarchy_content is empty or no fence is found in body.
    """
    if not hierarchy_content:
        return body
    replacement = (
        "<!-- AGENTTEAMS:BEGIN authority_hierarchy -->"
        + hierarchy_content
        + "<!-- AGENTTEAMS:END authority_hierarchy -->"
    )
    new_body, n = _AUTH_HIER_FENCE_RE.subn(replacement, body, count=1)
    return new_body if n > 0 else body


def _goosehints_content(project_name: str) -> str:
    """Return the .goosehints integrator content, parameterized to the project name.

    The Session Startup block (below the managed fence) instructs Goose to
    self-load the orchestrator recipe at plain-session start — VSCode extension,
    `goose session`, or any ACP session — without requiring `goose run --recipe`.
    It lives outside the managed fence so it survives --bridge-merge and --merge
    cycles unchanged.  See W7 in the integration plan.
    """
    return (
        "@AGENTS.md\n\n"
        "<!-- AGENTTEAMS:BEGIN goose-operational-notes -->\n"
        "## Goose operational notes (generated by agentteams)\n\n"
        "This team's canonical brief is AGENTS.md (included above). Entry point:\n\n"
        "    goose run --recipe .goose/recipes/orchestrator.yaml\n\n"
        "Delegation model:\n"
        "- The orchestrator recipe delegates to specialist recipes via `sub_recipes`\n"
        "  (each runs in its own isolated session).\n"
        "- Goose forbids nested delegation, so specialists reference cross-cutting\n"
        '  agents in-context with the `summon` `load("<recipe-slug>")` tool rather\n'
        "  than spawning a sub-agent. The relevant `load(...)` calls are listed in\n"
        '  each specialist recipe under "Delegation & references (Goose)".\n'
        "<!-- AGENTTEAMS:END goose-operational-notes -->\n\n"
        "### Session Startup (Mandatory)\n\n"
        f"**At the start of every session** in {project_name}, before responding to any user request:\n\n"
        "1. Read `.goose/recipes/orchestrator.yaml` using your file tool — this is your complete\n"
        "   role definition, constitutional rules, routing table, and all workflows\n"
        "2. Adopt the Orchestrator identity, constitutional rules, and routing logic from that\n"
        "   file for the entire session\n"
        "3. You are the **Orchestrator** for this project; do not perform domain work directly —\n"
        "   route all requests through the appropriate specialist agent\n\n"
        "This startup read applies to plain interactive sessions and IDE extension sessions equally.\n"
        "`goose run --recipe .goose/recipes/orchestrator.yaml` is the alternative that pre-loads\n"
        "automatically without the startup read.\n"
    )


class GooseAdapter(FrameworkAdapter):

    @property
    def framework_id(self) -> str:
        return "goose"

    def render_agent_file(self, content: str, agent_slug: str, manifest: dict[str, Any]) -> str:
        """Transform a rendered agent (VS Code-style markdown) into a Goose recipe."""
        name, description = _extract_name_description(content, agent_slug, manifest)
        handoffs = self.extract_handoffs(content)

        body = self._strip_yaml_front_matter(content)
        body = self._strip_handoffs_section(body).strip()
        if not body:
            body = description or name

        # W3: substitute project-specific authority hierarchy when available.
        source_instructions = manifest.get("_source_instructions_content", "")
        if source_instructions:
            hierarchy = _extract_authority_hierarchy(source_instructions)
            body = _substitute_authority_hierarchy(body, hierarchy)

        team = _team_slugs(manifest)
        targets = _dedupe_by_agent(
            h for h in handoffs
            if h.get("agent") in team and h.get("agent") != agent_slug
        )

        extensions = ["developer"]

        if agent_slug == "orchestrator":
            sub_recipes = [
                {
                    "name": _tool_name(h["agent"]),
                    "path": f"./{h['agent']}.yaml",
                    "description": h.get("label") or h.get("prompt") or "",
                }
                for h in targets
            ]
            # W4: supplement sub_recipes with team agents absent from handoffs:.
            # Agents in the team roster but missing from the handoffs: block are still
            # valid delegation targets; include them at the end with empty descriptions.
            target_slugs = frozenset(h["agent"] for h in targets)
            for slug in sorted(team - target_slugs - frozenset([agent_slug])):
                sub_recipes.append({
                    "name": _tool_name(slug),
                    "path": f"./{slug}.yaml",
                    "description": "",
                })
            if sub_recipes:
                extensions.append("summon")
            return _emit_recipe(
                title=name,
                description=description,
                instructions=body,
                extensions=extensions,
                sub_recipes=sub_recipes or None,
                # W6: probe prompt enables non-interactive `goose run --recipe` in CI.
                prompt=_ORCHESTRATOR_PROBE_PROMPT,
            )

        # Non-orchestrator agent: depth-1 delegate whose own handoffs are
        # depth-2 -> represent them as `load(...)` references, not delegation.
        if targets:
            body = body + "\n\n" + _load_section(targets)
            extensions.append("summon")
        return _emit_recipe(
            title=name,
            description=description,
            instructions=body,
            extensions=extensions,
        )

    def render_instructions_file(self, content: str, manifest: dict[str, Any]) -> str:
        """The team brief becomes AGENTS.md verbatim (strip any stray front matter).

        W3: If source copilot-instructions.md content is available in the manifest,
        propagate its project-specific authority_hierarchy into the AGENTS.md body.
        """
        body = self._strip_yaml_front_matter(content)
        source_instructions = manifest.get("_source_instructions_content", "")
        if source_instructions:
            hierarchy = _extract_authority_hierarchy(source_instructions)
            body = _substitute_authority_hierarchy(body, hierarchy)
        return body

    def render_builder_file(self, content: str, manifest: dict[str, Any]) -> str:
        """Wrap the team-builder meta-agent as a runnable Goose recipe.

        Goose agents are recipe YAML, so the builder cannot ship as a stray
        markdown file in ``.goose/recipes/``. It is a standalone recipe (no
        ``sub_recipes`` — it is not the orchestrator) with the ``developer``
        extension so it can write the description file and invoke build_team.
        Run it with ``goose run --recipe .goose/recipes/team-builder.yaml``.
        """
        name, description = _extract_name_description(content, "team-builder", manifest)
        body = self._strip_yaml_front_matter(content)
        body = self._strip_handoffs_section(body).strip() or description or name
        return _emit_recipe(
            title=name or "Team Builder",
            description=description,
            instructions=body,
            extensions=["developer"],
        )

    def get_file_extension(self, file_type: str) -> str:
        if file_type in {"agent", "builder"}:
            return ".yaml"
        return ".md"

    def supports_handoffs(self) -> bool:
        return True

    def handoff_delivery_mode(self) -> str:
        # Handoffs are encoded directly into recipes (sub_recipes / load), so no
        # sidecar manifest is needed.
        return "native"

    def get_agents_dir(self, project_path: Path) -> Path:
        return project_path / ".goose" / "recipes"

    def normalize_output_path(self, output: Path) -> Path:
        """Normalize a user-supplied --output path for the Goose framework.

        The Goose agents directory is <project>/.goose/recipes/. When a user
        passes --output <project-root> (including `--output .`), the path does
        not end in .goose/recipes and agentteams must append the suffix so that
        the relative paths emitted by finalize_output_path (../../AGENTS.md, etc.)
        resolve correctly within the project tree.

        If the path already ends in `.goose/recipes` or `.goose` it is returned
        as-is (or with `/recipes` appended for the `.goose` case).
        """
        parts = output.parts
        if len(parts) >= 2 and parts[-2] == ".goose" and parts[-1] == "recipes":
            return output  # already the recipes directory
        if len(parts) >= 1 and parts[-1] == ".goose":
            return output / "recipes"
        # Treat as project root → derive the agents dir.
        return output / ".goose" / "recipes"

    def finalize_output_path(self, rel_path: str, file_type: str) -> str:
        """Map the generic instructions path to repo-root AGENTS.md.

        The planned instructions path is ``../copilot-instructions.md`` (relative
        to the agents dir). For Goose the agents dir is ``.goose/recipes``, so the
        repo root is two levels up.
        """
        if file_type == "instructions" and rel_path.endswith("copilot-instructions.md"):
            return "../../AGENTS.md"
        return super().finalize_output_path(rel_path, file_type)

    def extra_output_files(self, manifest: dict[str, Any]) -> list[tuple[str, str]]:
        """Emit the repo-root .goosehints integrator alongside AGENTS.md.

        W7: The content now includes a Session Startup block (below the managed
        fence) so plain `goose session` and VSCode extension sessions automatically
        adopt the Orchestrator role without requiring `goose run --recipe`.
        """
        project_name = manifest.get("project_name", "this project")
        return [("../../.goosehints", _goosehints_content(project_name))]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_YAML_FRONT_MATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
_YAML_SCALAR_RE = re.compile(r'^([a-zA-Z][a-zA-Z0-9_-]*)\s*:\s*"?([^"\n]+)"?\s*$', re.MULTILINE)


def _tool_name(slug: str) -> str:
    """Goose generates a tool name per sub-recipe; keep it identifier-safe."""
    return re.sub(r"[^a-z0-9_]", "_", slug.replace("-", "_").lower())


def _dedupe_by_agent(handoffs: Any) -> list[dict[str, Any]]:
    """Keep one handoff per target agent (first wins, i.e. the YAML block entry).

    The base ``extract_handoffs`` dedupes on (agent, prompt), so an agent named
    in both the YAML ``handoffs:`` block and the body ``## Handoff Instructions``
    survives twice. Goose needs exactly one sub_recipe / load per target agent.
    """
    seen: set[str] = set()
    out: list[dict[str, Any]] = []
    for h in handoffs:
        agent = str(h.get("agent", ""))
        if not agent or agent in seen:
            continue
        seen.add(agent)
        out.append(h)
    return out


def _team_slugs(manifest: dict[str, Any]) -> frozenset[str]:
    """Slugs of agents generated for this team (valid handoff/load targets)."""
    slugs: set[str] = {"orchestrator"}
    slugs.update(manifest.get("adopted_agents", []))
    for f in manifest.get("output_files", []):
        name = Path(f.get("path", "")).name
        if name.endswith(".agent.md"):
            slugs.add(name[: -len(".agent.md")])
    return frozenset(slugs)


def _extract_name_description(
    content: str,
    agent_slug: str,
    manifest: dict[str, Any],
) -> tuple[str, str]:
    """Pull (name, description) from VS Code YAML front matter, with fallbacks."""
    name = ""
    description = ""
    match = _YAML_FRONT_MATTER_RE.match(content)
    if match:
        for key_match in _YAML_SCALAR_RE.finditer(match.group(1)):
            key = key_match.group(1).strip()
            val = key_match.group(2).strip().strip("\"'")
            if key == "name" and not name:
                name = val
            elif key == "description" and not description:
                description = val
    if not name:
        project_name = manifest.get("project_name", "")
        agent_name = FrameworkAdapter._slug_to_name(agent_slug)
        name = f"{agent_name} — {project_name}" if project_name else agent_name
    return name, description


def _load_section(targets: list[dict[str, Any]]) -> str:
    """Render the depth-2 reference block (load instead of nested delegation)."""
    lines = [
        "## Delegation & references (Goose)",
        "",
        "Goose forbids nested delegation, so when you need another specialist's "
        "guidance, load that recipe into your own context with the `summon` "
        "`load` tool (do not try to spawn a sub-agent):",
        "",
    ]
    for h in targets:
        slug = h["agent"]
        label = h.get("label") or h.get("prompt") or slug
        lines.append(
            f'- **{label}** — call `load("{slug}")` to bring `{slug}`\'s '
            f"instructions into context, then act on them here."
        )
    return "\n".join(lines)


def _yaml_dq(value: str) -> str:
    """Return a single-line double-quoted YAML scalar."""
    s = (value or "").replace("\\", "\\\\").replace('"', '\\"')
    s = s.replace("\r", " ").replace("\n", " ").strip()
    return f'"{s}"'


def _indent_block(body: str, indent: str = "  ") -> str:
    """Indent body for a YAML literal block scalar (blank lines stay empty)."""
    out: list[str] = []
    for line in body.split("\n"):
        out.append(indent + line if line.strip() else "")
    return "\n".join(out)


def _emit_recipe(
    *,
    title: str,
    description: str,
    instructions: str,
    extensions: list[str],
    sub_recipes: list[dict[str, str]] | None = None,
    prompt: str | None = None,
) -> str:
    """Serialize a Goose recipe to YAML (hand-built, schema version 1.0.0).

    W6: The optional `prompt` field, when provided, is emitted after `description`
    and enables non-interactive `goose run --recipe` execution in CI pipelines
    (the --recipe and --text flags are mutually exclusive in Goose CLI).
    """
    lines: list[str] = [
        f'version: "{_RECIPE_VERSION}"',
        f"title: {_yaml_dq(title)}",
        f"description: {_yaml_dq(description or title)}",
    ]
    if prompt is not None:
        lines.append(f"prompt: {_yaml_dq(prompt)}")
    lines += [
        "instructions: |",
        _indent_block(instructions),
        "extensions:",
    ]
    for ext in extensions:
        if ext == "developer":
            lines += [
                "  - type: builtin",
                "    name: developer",
                "    bundled: true",
                "    timeout: 300",
            ]
        elif ext == "summon":
            lines += [
                "  - type: platform",
                "    name: summon",
            ]
    if sub_recipes:
        lines.append("sub_recipes:")
        for sr in sub_recipes:
            lines.append(f"  - name: {_yaml_dq(sr['name'])}")
            lines.append(f"    path: {_yaml_dq(sr['path'])}")
            if sr.get("description"):
                lines.append(f"    description: {_yaml_dq(sr['description'])}")
    return "\n".join(lines).rstrip() + "\n"
