"""Files the Goose adapter emits alongside its recipes.

Carved out of ``agentteams/frameworks/goose.py`` on 2026-07-31: single-sourcing the research
capability guidance pushed that module past the CH-07 ceiling, and the CH-07 ratchet refused the
commit. The seam was already there — these three functions build *document content* (a hints
integrator, a capabilities reference, a shipped script) while the rest of ``goose.py`` is adapter
behaviour: recipe emission, extension scoping, YAML validation, handoff mapping.

They share one property worth stating, because ``AUTHORING-GUIDE.md`` §6 now names it as a
recurring trap: none of them receives the team manifest. They see the project name and nothing
else, so any content here that depends on team composition must be phrased verify-first
("check whether X before assuming") rather than asserted outright.

Re-exported from ``agentteams.frameworks.goose`` so existing imports keep working.
"""

from __future__ import annotations

from pathlib import Path

from agentteams.capability_hints import RESEARCH_CAPABILITY_BULLET

__all__ = [
    "_goosehints_content",
    "_resilient_runner_content",
    "_goose_capabilities_content",
    "_RESILIENT_RUNNER_SOURCE",
]


def _goosehints_content(project_name: str) -> str:
    """Return the .goosehints integrator content, parameterized to the project name.

    The Session Startup block (below the managed fence) instructs Goose to
    self-load the orchestrator recipe at plain-session start — VSCode extension,
    `goose session`, or any ACP session — without requiring `goose run --recipe`.
    It lives outside the managed fence so it survives --bridge-merge and --merge
    cycles unchanged.  See W7 in the integration plan.
    """
    return (
        "@AGENTS.md\n\n"
        "<!-- AGENTTEAMS:BEGIN goose_operational_notes v=1 -->\n"
        "## Goose operational notes (generated by agentteams)\n\n"
        "This team's canonical brief is AGENTS.md (included above). Entry point:\n\n"
        "    goose run --recipe .goose/recipes/orchestrator.yaml\n\n"
        "Delegation model:\n"
        "- The orchestrator recipe delegates to specialist recipes via `sub_recipes`\n"
        "  (each runs in its own isolated session).\n"
        "- Goose forbids nested delegation, so specialists reference cross-cutting\n"
        '  agents in-context with the `summon` `load("<recipe-slug>")` tool rather\n'
        "  than spawning a sub-agent. The relevant `load(...)` calls are listed in\n"
        '  each specialist recipe under "Delegation & references (Goose)".\n'
        "<!-- AGENTTEAMS:END goose_operational_notes -->\n\n"
        "### Session Startup (Mandatory)\n\n"
        f"**At the start of every session** in {project_name}, before responding to any user request:\n\n"
        "1. Read `.goose/recipes/orchestrator.yaml` using your file tool — this is your complete\n"
        "   role definition, constitutional rules, routing table, and all workflows\n"
        "2. Adopt the Orchestrator identity, constitutional rules, and routing logic from that\n"
        "   file for the entire session\n"
        "3. You are the **Orchestrator** for this project; do not perform domain work directly —\n"
        "   route all requests through the appropriate specialist agent\n\n"
        "This startup read applies to plain interactive sessions and IDE extension sessions equally.\n"
        "`goose run --recipe .goose/recipes/orchestrator.yaml` is the alternative that pre-loads\n"
        "automatically without the startup read.\n\n"
        "See `.goose/recipes/references/goose-capabilities-reference.md` for what your tools\n"
        "can actually do — in particular, the default `developer` extension's shell has no\n"
        "network sandbox, which its own built-in prompt never mentions.\n\n"
        "If a turn ever ends with no response and no error, see `scripts/goose-run-resilient.py`\n"
        "(repo root) — a wrapper that detects that exact symptom and auto-continues.\n"
    )


_RESILIENT_RUNNER_SOURCE = Path(__file__).resolve().parent.parent.parent / "scripts" / "goose-run-resilient.py"


def _resilient_runner_content() -> str:
    """Return this repo's own `scripts/goose-run-resilient.py`, read from disk.

    Gap 3 (2026-07-24): every generated/bridged Goose team ships its own copy of the
    dead-turn-detecting `goose run` wrapper, unconditionally (no manifest opt-in) —
    unlike `recipe_retry` (Phase-4c), which structurally alters the emitted recipe
    YAML and re-run behavior the instant it's declared, and unlike
    `_scoped_builtin_extensions`, which changes an existing agent's tool access. A
    sibling script that sits unused in `scripts/` unless separately invoked is not
    the same risk class as either, so it does not need the same opt-in gate — see
    `references/plans/goose-openrouter-tool-call-reasoning-leak-2026-07-24.report.md`
    and `tmp/by-week/2026-W30/goose-openrouter-resilience-integration.plan.md` for
    the full investigation and plan-level audit this decision was checked against.

    Read from disk (not inline-duplicated) so the shipped copy can never drift from
    the tested one, mirroring the schema-loading pattern in
    ``mcp_emit.py``'s ``_validator()`` (``Path(__file__).resolve().parent.parent /
    "schemas" / "mcp-server.schema.json"``). Degrades to an explanatory placeholder
    (never a crash) if the source file is unexpectedly missing from the install.
    """
    try:
        return _RESILIENT_RUNNER_SOURCE.read_text(encoding="utf-8")
    except OSError:
        return (
            "#!/usr/bin/env python3\n"
            '"""Placeholder: scripts/goose-run-resilient.py was not found in this\n'
            "agentteams install (expected at "
            f"{_RESILIENT_RUNNER_SOURCE}). Reinstall agentteams or fetch the file\n"
            "from the agentteams source repo.\n"
            '"""\n'
        )


def _goose_capabilities_content(project_name: str) -> str:
    """Return the capabilities-reference content emitted to every generated Goose team.

    Diagnosed gap (2026-07-23): Goose's `developer` extension ships by default for
    effectively every agent (see ``_scoped_builtin_extensions``), and its built-in
    system prompt frames the shell tool purely as a coding tool ("build software and
    operate a terminal," "prefer rg," "use python3") without ever mentioning that the
    same shell has unrestricted network access. Agents therefore under-use `curl`/
    `wget` for external retrieval and instead report "no tool for this," even when a
    plain shell command would work. This file states that fact explicitly for every
    generated team, since it's true regardless of which optional extensions a given
    team's agents additionally enable.

    Deliberately does NOT assert that any opt-in extension (e.g. ``computercontroller``)
    is active — only ``developer`` is presumed present. Doing otherwise would repeat the
    original bug's own failure mode: telling an agent a tool exists that was never wired
    into its recipe's ``extensions:`` block for that specific team.
    """
    return (
        f"# Goose CLI Capabilities Reference — {project_name}\n\n"
        "This file documents what Goose's builtin extensions can actually do, and how to\n"
        "tell which ones are wired in for *you specifically*. It is generated once per\n"
        "project and does not change as agents are added or removed.\n\n"
        "## Check your own capability set first\n\n"
        "Only the extensions listed in **your own** `.goose/recipes/<your-slug>.yaml`\n"
        "`extensions:` block are callable by you. This reference describes what each\n"
        "builtin extension can do *if present* — it is not a claim that every extension\n"
        "listed below is active for every agent in this team. When in doubt, read your\n"
        "own recipe file.\n\n"
        "## `developer` — present for effectively every agent by default\n\n"
        "Read/write files and execute shell commands. The shell tool has **no code-level\n"
        "network sandbox**: `curl`, `wget`, and any other CLI network client work exactly\n"
        "as they would in a normal terminal, unless a specific deployment has deliberately\n"
        "restricted egress. The extension's own built-in system prompt frames this tool\n"
        "entirely around software work (reading/editing code, running tests, using `rg`)\n"
        "and never mentions network use — do not treat that framing as a capability limit.\n"
        "If a user asks for something that needs live external data (a webpage, an API\n"
        "response, a public data feed) and no dedicated fetch/search extension is listed in\n"
        "your own recipe, try a plain shell command (e.g. `curl <url>`) before concluding\n"
        "you have no way to retrieve it.\n\n"
        "## Other builtin extensions (opt-in per agent, via `recipe_extensions`)\n\n"
        "These are **not** enabled unless your own recipe's `extensions:` block lists them:\n\n"
        "- `computercontroller` — web scraping (`web_scrape`: fetch a URL's content), file\n"
        "  caching, PDF/DOCX/XLSX manipulation, and local automation scripts. The closest\n"
        "  thing to a dedicated fetch tool; prefer it over ad hoc shell `curl` when it's\n"
        "  available, since it handles content-type negotiation and caching for you.\n"
        "- `summon` — load referenced recipes/skills into your own context, or delegate to\n"
        "  a sub-recipe session (orchestrator only; Goose forbids nested delegation beyond\n"
        "  one layer).\n"
        "- `apps`, `skills`, `todo`, `analyze`, `memory`, `autovisualiser` — local,\n"
        "  non-network tools for sandboxed HTML apps, skill discovery, task tracking, code\n"
        "  structure analysis, durable memory, and data visualization respectively.\n\n"
        # Deliberately does NOT restate "no builtin does web search" — that claim is owned by
        # RESEARCH_CAPABILITY_BULLET, embedded in the next section. Stating it here too is how
        # two differently-worded copies appeared the first time. What stays is the part that is
        # genuinely Goose-specific: search CAN be added as an MCP extension, so check the brief.
        "Web *search* is covered in the next section. One Goose-specific route not mentioned\n"
        "there: a search MCP extension (e.g. a Brave/Tavily/DuckDuckGo server) can be added via\n"
        "`recipe_extensions`/`goose:mcp` in this team's brief — check whether one is configured\n"
        "before assuming search is unavailable outright.\n\n"
        "## Capability that isn't a Goose extension at all\n\n"
        "Not part of the `recipe_extensions` opt-in list above — reached through `developer`'s\n"
        "ordinary shell instead, the same way any other installed CLI tool would be, no MCP\n"
        "wiring needed:\n\n"
        # Single-sourced from agentteams/capability_hints.py, which agentteams/bridge.py also
        # consumes for the bridged AGENTS.md. This section previously restated the same facts in
        # its own words; two differently-worded copies of one capability claim is the divergence
        # the shared constant exists to prevent, and it had already recurred once. The Goose-only
        # framing that genuinely belongs to THIS document (the browser/renderer contrast with
        # `computercontroller`) stays below, because it is about a Goose extension.
        + RESEARCH_CAPABILITY_BULLET
        + "\nSeparately: none of the builtin extensions execute JavaScript or drive a real\n"
        "browser — `computercontroller`'s `web_scrape` is a plain fetch, not a renderer. A page\n"
        "that needs JavaScript to show its real content is a job for\n"
        "`python -m agentteams.research browser \"<url>\"` (that module's separate `[browser]`\n"
        "extra, if installed), not an extension. See\n"
        "`references/skill-generation.reference.md`'s worked example (\"a page `fetch` can't\n"
        "render\") for the full tiered approach and its security-review gate.\n\n"
        "## General CLI competency (not Goose-specific)\n\n"
        "See `references/cli-tool-discovery.reference.md` for the runtime-agnostic\n"
        "methodology this file's `developer`/network guidance above is one instance of:\n"
        "discovering what's actually installed, using `--help`/`man`, inspecting a program\n"
        "as a last resort, and installing a genuinely missing tool. See\n"
        "`references/skill-generation.reference.md` for what to do when a capability is\n"
        "still out of reach after trying that.\n\n"
        "## Context-bloat management (built into Goose, not something to prompt for)\n\n"
        "Goose already auto-compacts a long-running conversation on its own — this is a real,\n"
        "harness-level feature (`goose::context_mgmt`), not something an agent needs to\n"
        "monitor or trigger itself. `/compact` is a genuine Goose slash command, and Goose\n"
        "already calls it automatically once accumulated context crosses a configurable\n"
        "fraction of the model's context window, summarizing rather than truncating so the\n"
        "conversation's signal survives the compaction. Don't write agent instructions telling\n"
        "a persona to \"check context usage and call /compact\" — the harness already does this\n"
        "unconditionally, and an agent's own generated text isn't re-parsed as a slash command\n"
        "by the harness, so such an instruction would be inert.\n\n"
        "The one thing that IS configurable is the threshold: `GOOSE_AUTO_COMPACT_THRESHOLD`\n"
        "(env var) / `autoCompactThreshold` (the same setting's name in Goose's ACP protocol,\n"
        "used by IDE integrations like the VS Code extension) — a fraction, `(0, 1]`, e.g.\n"
        "`0.9` for 90%. It is not exposed in the interactive `goose configure` wizard and has\n"
        "no recipe-level equivalent (`.goose/recipes/*.yaml` has no settings-override block) —\n"
        "it is set the same way as `GOOSE_MODE`/`GOOSE_DEBUG`, as a flat top-level key in that\n"
        "Goose installation's own `~/.config/goose/config.yaml`. This project's generator has\n"
        "no mechanism to set it on a downstream user's behalf — that file lives outside every\n"
        "project directory this module writes to. A team that wants a specific threshold must\n"
        "set it directly in their own Goose installation.\n"
    )
