"""
goose.py — Framework adapter for Block / AAIF "Goose" recipes.

Agent files:  .goose/recipes/<slug>.yaml   (Goose recipe format)
Instructions: AGENTS.md (repo root) + .goosehints (repo root, integrates AGENTS.md)
Format:       Recipe YAML (title, description, instructions, extensions, sub_recipes)
Delegation:   orchestrator handoffs -> sub_recipes  (one delegation layer, native);
              every other agent's handoffs -> `summon` `load(...)` references.

Why this mapping
----------------
agentteams produces an orchestrator that delegates to specialist agents, and
specialists in turn hand off to cross-cutting agents (security, git-operations,
cleanup, ...). Goose caps delegation at ONE layer — a sub-recipe/subagent cannot
spawn another (source: SessionType::SubAgent guard in goose's summon platform
extension). We therefore reinterpret the agentteams handoff DAG faithfully:

  * Depth 0 (orchestrator) -> a recipe declaring `summon` + `sub_recipes` of its
    direct handoff targets. This is TRUE delegation (isolated child sessions).
  * Depth 1+ (every other agent) -> a recipe. Its own handoffs are depth-2 by
    construction, so they are rewritten as `summon` `load("<slug>")` directives
    inside the recipe instructions: the agent loads the referenced recipe's
    content into ITS OWN context instead of spawning a nested delegate. No
    handoff edge is dropped; deeper structure is preserved as references.

See references/plans/goose-integration.plan.md §10 for the full standardized model. The Goose
recipe schema is pinned at version 1.0.0; YAML is emitted by hand (the codebase
intentionally avoids a YAML dependency and parses front matter with regex).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .base import FrameworkAdapter

# ---------------------------------------------------------------------------
# Recipe constants
# ---------------------------------------------------------------------------

_RECIPE_VERSION = "1.0.0"

# The `.goosehints` integrator (repo root). Goose reads `.goosehints` by default
# (CONTEXT_FILE_NAMES default is [".goosehints", "AGENTS.md"]); the leading
# `@AGENTS.md` content-include guarantees the canonical team brief reaches the
# system prompt even when a project customizes CONTEXT_FILE_NAMES to exclude
# AGENTS.md. See references/plans/goose-integration.plan.md §10.4.
_GOOSEHINTS = """@AGENTS.md

Goose operational notes (generated by agentteams)

This team's canonical brief is AGENTS.md (included above). Entry point:

    goose run --recipe .goose/recipes/orchestrator.yaml

Delegation model:
- The orchestrator recipe delegates to specialist recipes via `sub_recipes`
  (each runs in its own isolated session).
- Goose forbids nested delegation, so specialists reference cross-cutting
  agents in-context with the `summon` `load("<recipe-slug>")` tool rather than
  spawning a sub-agent. The relevant `load(...)` calls are listed in each
  specialist recipe under "Delegation & references (Goose)".
"""


class GooseAdapter(FrameworkAdapter):

    @property
    def framework_id(self) -> str:
        return "goose"

    def render_agent_file(self, content: str, agent_slug: str, manifest: dict[str, Any]) -> str:
        """Transform a rendered agent (VS Code-style markdown) into a Goose recipe."""
        name, description = _extract_name_description(content, agent_slug, manifest)
        handoffs = self.extract_handoffs(content)

        body = self._strip_yaml_front_matter(content)
        body = self._strip_handoffs_section(body).strip()
        if not body:
            body = description or name

        team = _team_slugs(manifest)
        targets = _dedupe_by_agent(
            h for h in handoffs
            if h.get("agent") in team and h.get("agent") != agent_slug
        )

        extensions = ["developer"]

        if agent_slug == "orchestrator":
            sub_recipes = [
                {
                    "name": _tool_name(h["agent"]),
                    "path": f"./{h['agent']}.yaml",
                    "description": h.get("label") or h.get("prompt") or "",
                }
                for h in targets
            ]
            if sub_recipes:
                extensions.append("summon")
            return _emit_recipe(
                title=name,
                description=description,
                instructions=body,
                extensions=extensions,
                sub_recipes=sub_recipes or None,
            )

        # Non-orchestrator agent: depth-1 delegate whose own handoffs are
        # depth-2 -> represent them as `load(...)` references, not delegation.
        if targets:
            body = body + "\n\n" + _load_section(targets)
            extensions.append("summon")
        return _emit_recipe(
            title=name,
            description=description,
            instructions=body,
            extensions=extensions,
        )

    def render_instructions_file(self, content: str, manifest: dict[str, Any]) -> str:
        """The team brief becomes AGENTS.md verbatim (strip any stray front matter)."""
        return self._strip_yaml_front_matter(content)

    def get_file_extension(self, file_type: str) -> str:
        if file_type == "agent":
            return ".yaml"
        return ".md"

    def supports_handoffs(self) -> bool:
        return True

    def handoff_delivery_mode(self) -> str:
        # Handoffs are encoded directly into recipes (sub_recipes / load), so no
        # sidecar manifest is needed.
        return "native"

    def get_agents_dir(self, project_path: Path) -> Path:
        return project_path / ".goose" / "recipes"

    def finalize_output_path(self, rel_path: str, file_type: str) -> str:
        """Map the generic instructions path to repo-root AGENTS.md.

        The planned instructions path is ``../copilot-instructions.md`` (relative
        to the agents dir). For Goose the agents dir is ``.goose/recipes``, so the
        repo root is two levels up.
        """
        if file_type == "instructions" and rel_path.endswith("copilot-instructions.md"):
            return "../../AGENTS.md"
        return super().finalize_output_path(rel_path, file_type)

    def extra_output_files(self, manifest: dict[str, Any]) -> list[tuple[str, str]]:
        """Emit the repo-root .goosehints integrator alongside AGENTS.md."""
        return [("../../.goosehints", _GOOSEHINTS)]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_YAML_FRONT_MATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
_YAML_SCALAR_RE = re.compile(r'^([a-zA-Z][a-zA-Z0-9_-]*)\s*:\s*"?([^"\n]+)"?\s*$', re.MULTILINE)


def _tool_name(slug: str) -> str:
    """Goose generates a tool name per sub-recipe; keep it identifier-safe."""
    return re.sub(r"[^a-z0-9_]", "_", slug.replace("-", "_").lower())


def _dedupe_by_agent(handoffs: Any) -> list[dict[str, Any]]:
    """Keep one handoff per target agent (first wins, i.e. the YAML block entry).

    The base ``extract_handoffs`` dedupes on (agent, prompt), so an agent named
    in both the YAML ``handoffs:`` block and the body ``## Handoff Instructions``
    survives twice. Goose needs exactly one sub_recipe / load per target agent.
    """
    seen: set[str] = set()
    out: list[dict[str, Any]] = []
    for h in handoffs:
        agent = str(h.get("agent", ""))
        if not agent or agent in seen:
            continue
        seen.add(agent)
        out.append(h)
    return out


def _team_slugs(manifest: dict[str, Any]) -> frozenset[str]:
    """Slugs of agents generated for this team (valid handoff/load targets)."""
    slugs: set[str] = {"orchestrator"}
    slugs.update(manifest.get("adopted_agents", []))
    for f in manifest.get("output_files", []):
        name = Path(f.get("path", "")).name
        if name.endswith(".agent.md"):
            slugs.add(name[: -len(".agent.md")])
    return frozenset(slugs)


def _extract_name_description(
    content: str,
    agent_slug: str,
    manifest: dict[str, Any],
) -> tuple[str, str]:
    """Pull (name, description) from VS Code YAML front matter, with fallbacks."""
    name = ""
    description = ""
    match = _YAML_FRONT_MATTER_RE.match(content)
    if match:
        for key_match in _YAML_SCALAR_RE.finditer(match.group(1)):
            key = key_match.group(1).strip()
            val = key_match.group(2).strip().strip("\"'")
            if key == "name" and not name:
                name = val
            elif key == "description" and not description:
                description = val
    if not name:
        project_name = manifest.get("project_name", "")
        agent_name = FrameworkAdapter._slug_to_name(agent_slug)
        name = f"{agent_name} — {project_name}" if project_name else agent_name
    return name, description


def _load_section(targets: list[dict[str, Any]]) -> str:
    """Render the depth-2 reference block (load instead of nested delegation)."""
    lines = [
        "## Delegation & references (Goose)",
        "",
        "Goose forbids nested delegation, so when you need another specialist's "
        "guidance, load that recipe into your own context with the `summon` "
        "`load` tool (do not try to spawn a sub-agent):",
        "",
    ]
    for h in targets:
        slug = h["agent"]
        label = h.get("label") or h.get("prompt") or slug
        lines.append(
            f'- **{label}** — call `load("{slug}")` to bring `{slug}`\'s '
            f"instructions into context, then act on them here."
        )
    return "\n".join(lines)


def _yaml_dq(value: str) -> str:
    """Return a single-line double-quoted YAML scalar."""
    s = (value or "").replace("\\", "\\\\").replace('"', '\\"')
    s = s.replace("\r", " ").replace("\n", " ").strip()
    return f'"{s}"'


def _indent_block(body: str, indent: str = "  ") -> str:
    """Indent body for a YAML literal block scalar (blank lines stay empty)."""
    out: list[str] = []
    for line in body.split("\n"):
        out.append(indent + line if line.strip() else "")
    return "\n".join(out)


def _emit_recipe(
    *,
    title: str,
    description: str,
    instructions: str,
    extensions: list[str],
    sub_recipes: list[dict[str, str]] | None = None,
) -> str:
    """Serialize a Goose recipe to YAML (hand-built, schema version 1.0.0)."""
    lines: list[str] = [
        f'version: "{_RECIPE_VERSION}"',
        f"title: {_yaml_dq(title)}",
        f"description: {_yaml_dq(description or title)}",
        "instructions: |",
        _indent_block(instructions),
        "extensions:",
    ]
    for ext in extensions:
        if ext == "developer":
            lines += [
                "  - type: builtin",
                "    name: developer",
                "    bundled: true",
                "    timeout: 300",
            ]
        elif ext == "summon":
            lines += [
                "  - type: platform",
                "    name: summon",
            ]
    if sub_recipes:
        lines.append("sub_recipes:")
        for sr in sub_recipes:
            lines.append(f"  - name: {_yaml_dq(sr['name'])}")
            lines.append(f"    path: {_yaml_dq(sr['path'])}")
            if sr.get("description"):
                lines.append(f"    description: {_yaml_dq(sr['description'])}")
    return "\n".join(lines).rstrip() + "\n"
