"""Is ``--output`` pointing where the operator meant?

**Materialised, not hypothetical.** A scratch render invoked with a *relative*
``--output .claude/agents`` resolved against an unexpected working directory and briefly
overwrote this repository's real agent tree with throwaway probe content. It was caught by
`git status` and recovered from the tool's own pre-write backup, but nothing in the CLI had
objected: a relative path was accepted with no validation even though it landed on an existing,
tracked, non-empty directory that the run had not created.

**Fails open, deliberately.** The overwhelmingly common invocation is
``--output .github/agents`` from a project root, onto a tracked, non-empty directory — a
completely legitimate update. A guard that refuses *that* is worse than the defect it prevents.
So this refuses only when it can positively identify the target as a **foreign** tree: tracked,
non-empty, and carrying no sign of ever having been generated by agentteams. Anything it cannot
classify gets a warning and proceeds. A false warning costs one line of output; a false refusal
breaks working workflows.

Absolute paths are never checked: an operator who typed a full path said where they meant.
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from typing import Any

from agentteams.backup import BACKUP_DIR_NAME as _BACKUP_DIR_NAME

#: Evidence that a directory is (or was) an agentteams output tree. Any one is enough — teams
#: generated before a given marker existed still carry the others.
_GENERATED_MARKERS: tuple[str, ...] = (
    "references/build-log.json",
    "references/delivery-receipt.json",
    _BACKUP_DIR_NAME,
    "SETUP-REQUIRED.md",
)

#: Substring identifying a file as fence-managed by this tool, checked when no marker file is
#: present (a partially-emitted or hand-pruned tree can lose the markers but keep the fences).
_FENCE_MARKER = "AGENTTEAMS:BEGIN"


def _is_git_tracked_dir(path: Path) -> bool:
    """Whether ``path`` contains files tracked by git.

    Args:
        path: Candidate output directory.

    Returns:
        True only when ``git ls-files`` reports at least one tracked entry under ``path``.
        False on any error — an unavailable or non-git environment must not produce a refusal.
    """
    try:
        result = subprocess.run(
            ["git", "-C", str(path), "ls-files", "--error-unmatch", "."],
            capture_output=True, text=True, check=False, timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return result.returncode == 0 and bool(result.stdout.strip())


def _looks_agentteams_generated(path: Path) -> bool:
    """Whether ``path`` shows any sign of being an agentteams output tree.

    Args:
        path: Candidate output directory.

    Returns:
        True when a marker file exists, or when any top-level markdown file carries an
        AGENTTEAMS fence. False only when nothing identifies it — which is what makes the
        directory "foreign" for the purposes of :func:`assess_output_target`.
    """
    for marker in _GENERATED_MARKERS:
        if (path / marker).exists():
            return True
    try:
        for candidate in list(path.glob("*.md"))[:40]:
            if _FENCE_MARKER in candidate.read_text(encoding="utf-8", errors="ignore"):
                return True
    except OSError:
        # Unreadable directory: cannot classify, so do not claim it is foreign.
        return True
    return False


def assess_output_target(raw_output: str | None, resolved: Path) -> str | None:
    """Return a refusal/warning message for a suspicious ``--output``, else ``None``.

    Args:
        raw_output: The ``--output`` value exactly as the operator typed it, or ``None``.
        resolved: The absolute path it resolved to.

    Returns:
        ``None`` when the target is fine or cannot be classified. Otherwise a message naming
        what was found and how to proceed deliberately.
    """
    if not raw_output or Path(raw_output).is_absolute():
        return None
    if not resolved.is_dir() or not any(resolved.iterdir()):
        return None
    if _looks_agentteams_generated(resolved):
        return None
    if not _is_git_tracked_dir(resolved):
        return None
    return (
        f"--output {raw_output!r} resolved to {resolved}, which is a non-empty, git-tracked "
        f"directory with no sign of being an agentteams-generated tree (no build log, delivery "
        f"receipt, backups, or AGENTTEAMS fences).\n"
        f"  cwd: {Path.cwd()}\n"
        f"A relative --output resolves against the current working directory, which is how a "
        f"scratch render once overwrote a real agent tree. If this is intended, pass an "
        f"absolute path or --allow-foreign-output."
    )


def resolve_output_dir(
    args: argparse.Namespace,
    adapter: Any,
    description: dict[str, Any],
) -> tuple[Path, Path]:
    """Resolve where this run writes, and to which project root.

    Lives beside :func:`assess_output_target` rather than in the pipeline: "which directory does
    this run write to, and is it the right one" is one question, and `cli/generate.py` is at the
    CH-07 line-count ceiling.

    Args:
        args: Parsed CLI namespace.
        adapter: The framework adapter (normalises framework-specific nested agent dirs).
        description: The loaded project description.

    Returns:
        ``(project_root, output_dir)``. ``project_root`` is the pre-normalisation path — the
        operator's project root — used as the base for the project-root ``.claude/`` MCP artifact.
    """
    if args.output:
        # W1: let the adapter normalize --output so framework-specific nested agents dirs
        # (e.g. Goose's .goose/recipes/) are derived correctly when the user passes a project
        # root, including `--output .`.
        project_root = Path(args.output).resolve()
        return project_root, adapter.normalize_output_path(project_root)
    if description.get("existing_project_path"):
        project_root = Path(description["existing_project_path"])
        return project_root, adapter.get_agents_dir(project_root)
    project_root = Path.cwd()
    return project_root, adapter.get_agents_dir(project_root)


def refuse_foreign_target(args: argparse.Namespace, output_dir: Path) -> str | None:
    """Return a refusal message when the run must not proceed, else ``None``.

    Args:
        args: Parsed CLI namespace (read for ``output`` and ``allow_foreign_output``).
        output_dir: The resolved write target.

    Returns:
        The refusal text, or ``None`` when the run may continue — including when the operator
        passed ``--allow-foreign-output``.
    """
    message = assess_output_target(args.output, output_dir)
    if message and not getattr(args, "allow_foreign_output", False):
        return message
    return None
