"""provenance.py — a small, reusable provenance stamp for generated artifacts.

**Why (architecture-quality feature: provenance stamping as a general pattern).** The red-team
scoring work learned that any generated artifact downstream work relies on should carry a
machine-readable record of *how it was obtained* — its inputs, the generator, and any
known-provisional flags — so a reader never mistakes a provisional snapshot for a settled result
(the honesty discipline, and Dong et al.'s contamination lesson: provenance is what lets a claim be
audited). The ratings CSV carried such a stamp by hand; this module makes the pattern reusable so
other generated artifacts (manifests, indices, eval outputs, fleet reports) can carry the same.

Design constraints:
- **stdlib-only** (the package's style rule); no external deps.
- **Deterministic given its inputs** — the caller supplies the timestamp (this package is used in
  contexts, e.g. workflow scripts, where an implicit ``datetime.now()`` is disallowed because it
  would break resume/reproducibility). Callers pass ``generated_at`` explicitly.
- **Honest by construction** — ``provisional`` is a required, explicit field, never defaulted to a
  reassuring value; a stamp with no provisional caveats must say so on purpose.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path


def _digest(path: Path) -> str:
    """Return a short sha256 of a file's bytes, or ``"<missing>"`` if absent."""
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()[:16]
    except OSError:
        return "<missing>"


@dataclass
class Provenance:
    """A machine-readable record of how a generated artifact was produced.

    Attributes:
        generator: The script/module that produced the artifact (e.g. its module path).
        generated_at: An ISO-8601 timestamp string. **Supplied by the caller** — this module never
            reads the clock itself (see the module docstring).
        inputs: ``{label: sha256-prefix}`` for each input the artifact was derived from. Use
            :meth:`with_input_files` to fill this from paths.
        provisional: Explicit, required list of provisional/known-limitation notes. An empty list is
            a deliberate assertion that nothing is known-provisional — never a silent default.
        notes: Free-form additional context.
    """

    generator: str
    generated_at: str
    inputs: dict[str, str] = field(default_factory=dict)
    provisional: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def with_input_files(self, **labelled_paths: Path) -> "Provenance":
        """Record a sha256 prefix for each labelled input path. Returns self for chaining."""
        for label, path in labelled_paths.items():
            self.inputs[label] = _digest(Path(path))
        return self

    def to_dict(self) -> dict:
        """Return the stamp as a JSON-serializable dict."""
        return {
            "generator": self.generator,
            "generated_at": self.generated_at,
            "inputs": dict(self.inputs),
            "provisional": list(self.provisional),
            "notes": list(self.notes),
        }

    def to_json(self) -> str:
        """Return the stamp as pretty JSON (for a ``*.provenance.json`` sidecar)."""
        return json.dumps(self.to_dict(), indent=2, sort_keys=True)

    def to_markdown(self) -> str:
        """Return the stamp as a compact markdown block (for embedding in a report)."""
        lines = [
            "<!-- provenance -->",
            f"**Provenance.** Generated by `{self.generator}` at {self.generated_at}.",
        ]
        if self.inputs:
            joined = ", ".join(f"`{k}`={v}" for k, v in sorted(self.inputs.items()))
            lines.append(f"Inputs: {joined}.")
        if self.provisional:
            lines.append("**Provisional / known limitations:**")
            lines.extend(f"- {p}" for p in self.provisional)
        else:
            lines.append("Provisional: none declared (deliberate).")
        for n in self.notes:
            lines.append(n)
        return "\n".join(lines)

    def write_sidecar(self, artifact_path: Path) -> Path:
        """Write ``<artifact>.provenance.json`` next to *artifact_path*; return the sidecar path."""
        sidecar = Path(artifact_path).with_suffix(Path(artifact_path).suffix + ".provenance.json")
        sidecar.write_text(self.to_json() + "\n", encoding="utf-8")
        return sidecar
